stages:
  - lint
  - tests
  - publish

.shared-env: &shared-env
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

lint:
  image: ruby:2.5
  stage: lint
  variables:
    <<: *shared-env
  script:
    - gem install rubocop -v 0.49.1
    - rubocop

tests:
  image: ruby:2.5
  stage: tests
  variables:
    <<: *shared-env
  script:
    - bundle
    - rake

publish:
  image: ruby:2.5
  only:
    - /^(\d+\.\d+\.\d+)$/
  stage: publish
  script:
    - export VERSION="${CI_COMMIT_TAG}"
    - bundle install
    - rake install
    - rake release
