lane :auth_test do
  connected_auth
end
lane :certs_test do
  connected_auth
  connected_certs(
    app_id: 'com.rgbapps.citizenscience'
  )
end
lane :upload_test do
  connected_auth
  connected_certs(
    app_id: 'com.rgbapps.citizenscience'
  )
  connected_upload(
    ipa_file: '../test_assets/test.ipa'
  )
end
